---
haproxy:
  build: ./haproxy
  ports:
    - '80:80'
    - '443:443'
    - '9999:9999'
  links:
    - web0
    - web1

web0:
  build: ./web
  environment:
    MACHINE: web0

web1:
  build: ./web
  environment:
    MACHINE: web1
